package Model;
// Generated Dec 15, 2015 5:43:23 PM by Hibernate Tools 4.3.1

/**
 * GramaNiladhari generated by hbm2java
 */
public class GramaNiladhari implements java.io.Serializable {

    private int gramaId;
    private User user;
    private String grade;
    private String division;

    public GramaNiladhari() {
    }

    public GramaNiladhari(int gramaId, User user) {
        this.gramaId = gramaId;
        this.user = user;
    }

    public GramaNiladhari(int gramaId, User user, String grade, String division) {
        this.gramaId = gramaId;
        this.user = user;
        this.grade = grade;
        this.division = division;
    }

    public int getGramaId() {
        return this.gramaId;
    }

    public void setGramaId(int gramaId) {
        this.gramaId = gramaId;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getGrade() {
        return this.grade;
    }

    public void setGrade(String grade) {
        this.grade = grade;
    }

    public String getDivision() {
        return this.division;
    }

    public void setDivision(String division) {
        this.division = division;
    }

}
