package Model;
// Generated Dec 15, 2015 5:43:23 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Parent generated by hbm2java
 */
public class Parent implements java.io.Serializable {

    private int parentId;
    private User user;
    private String nationality;
    private String religion;
    private String province;
    private String district;
    private String divisionSecretary;
    private String gramaDivision;
    private Set students = new HashSet(0);

    public Parent() {
    }

    public Parent(int parentId, User user) {
        this.parentId = parentId;
        this.user = user;
    }

    public Parent(int parentId, User user, String nationality, String religion, String province, String district, String divisionSecretary, String gramaDivision, Set students) {
        this.parentId = parentId;
        this.user = user;
        this.nationality = nationality;
        this.religion = religion;
        this.province = province;
        this.district = district;
        this.divisionSecretary = divisionSecretary;
        this.gramaDivision = gramaDivision;
        this.students = students;
    }

    public Parent(int parentId, User user, String nationality, String religion, String province, String district, String divisionSecretary, String gramaDivision) {
        this.parentId = parentId;
        this.user = user;
        this.nationality = nationality;
        this.religion = religion;
        this.province = province;
        this.district = district;
        this.divisionSecretary = divisionSecretary;
        this.gramaDivision = gramaDivision;
    }

    public int getParentId() {
        return this.parentId;
    }

    public void setParentId(int parentId) {
        this.parentId = parentId;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getNationality() {
        return this.nationality;
    }

    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    public String getReligion() {
        return this.religion;
    }

    public void setReligion(String religion) {
        this.religion = religion;
    }

    public String getProvince() {
        return this.province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getDistrict() {
        return this.district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    public String getDivisionSecretary() {
        return this.divisionSecretary;
    }

    public void setDivisionSecretary(String divisionSecretary) {
        this.divisionSecretary = divisionSecretary;
    }

    public String getGramaDivision() {
        return this.gramaDivision;
    }

    public void setGramaDivision(String gramaDivision) {
        this.gramaDivision = gramaDivision;
    }

    public Set getStudents() {
        return this.students;
    }

    public void setStudents(Set students) {
        this.students = students;
    }

}
