package Model;
// Generated Dec 15, 2015 5:43:23 PM by Hibernate Tools 4.3.1

/**
 * PastPupil generated by hbm2java
 */
public class PastPupil implements java.io.Serializable {

    private int ppId;
    private Student pastPupil;
    private Student student;
    private Integer toGrade;
    private Integer fromGrade;
    private Integer toYear;
    private Integer fromYear;

    public PastPupil() {
    }

    public PastPupil(int ppId, Student student) {
        this.ppId = ppId;
        this.student = student;
    }

    public PastPupil(int ppId, Student student, Integer toGrade, Integer fromGrade, Integer toYear, Integer fromYear) {
        this.ppId = ppId;
        this.student = student;
        this.toGrade = toGrade;
        this.fromGrade = fromGrade;
        this.toYear = toYear;
        this.fromYear = fromYear;
    }

    public PastPupil(int ppId, Student student, Student pastPupil, Integer toGrade, Integer fromGrade, Integer toYear, Integer fromYear) {
        this.ppId = ppId;
        this.student = student;
        this.toGrade = toGrade;
        this.fromGrade = fromGrade;
        this.toYear = toYear;
        this.fromYear = fromYear;
        this.pastPupil = pastPupil;
    }

    public int getPpId() {
        return this.ppId;
    }

    public void setPpId(int ppId) {
        this.ppId = ppId;
    }

    public Student getStudent() {
        return this.student;
    }

    public void setStudent(Student student) {
        this.student = student;
    }

    public Integer getToGrade() {
        return this.toGrade;
    }

    public void setToGrade(Integer toGrade) {
        this.toGrade = toGrade;
    }

    public Integer getFromGrade() {
        return this.fromGrade;
    }

    public void setFromGrade(Integer fromGrade) {
        this.fromGrade = fromGrade;
    }

    public Integer getToYear() {
        return this.toYear;
    }

    public void setToYear(Integer toYear) {
        this.toYear = toYear;
    }

    public Integer getFromYear() {
        return this.fromYear;
    }

    public void setFromYear(Integer fromYear) {
        this.fromYear = fromYear;
    }

    /**
     * @return the pastPupil
     */
    public Student getPastPupil() {
        return pastPupil;
    }

    /**
     * @param pastPupil the pastPupil to set
     */
    public void setPastPupil(Student pastPupil) {
        this.pastPupil = pastPupil;
    }

}
