package Model;
// Generated Dec 15, 2015 5:43:23 PM by Hibernate Tools 4.3.1

/**
 * Principal generated by hbm2java
 */
public class Principal implements java.io.Serializable {

    private int principalId;
    private School school;
    private User user;
    private String grade;

    public Principal() {
    }

    public Principal(int principalId, User user, School school) {
        this.principalId = principalId;
        this.user = user;
        this.school = school;
    }

    public Principal(int principalId, User user, School school, String grade) {
        this.principalId = principalId;
        this.user = user;
        this.school = school;
        this.grade = grade;
    }

    public int getPrincipalId() {
        return this.principalId;
    }

    public void setPrincipalId(int principalId) {
        this.principalId = principalId;
    }

    public School getSchool() {
        return this.school;
    }

    public void setSchool(School school) {
        this.school = school;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getGrade() {
        return this.grade;
    }

    public void setGrade(String grade) {
        this.grade = grade;
    }

}
