package Model;
// Generated Dec 15, 2015 5:43:23 PM by Hibernate Tools 4.3.1

/**
 * Registry generated by hbm2java
 */
public class Registry implements java.io.Serializable {

    private Integer registryId;
    private School school;
    private Student student;
    private Integer date;
    private String distance;
    private Integer pastpupilScore;
    private Integer siblingScore;
    private String distanceScore;
    private String registeredStatus;

    public Registry() {
    }

    public Registry(School school, Student student) {
        this.school = school;
        this.student = student;
    }

    public Registry(School school, Student student, Integer date, String distance, Integer pastpupilScore, Integer siblingScore, String distanceScore, String registeredStatus) {
        this.school = school;
        this.student = student;
        this.date = date;
        this.distance = distance;
        this.pastpupilScore = pastpupilScore;
        this.siblingScore = siblingScore;
        this.distanceScore = distanceScore;
        this.registeredStatus = registeredStatus;
    }

    public Integer getRegistryId() {
        return this.registryId;
    }

    public void setRegistryId(Integer registryId) {
        this.registryId = registryId;
    }

    public School getSchool() {
        return this.school;
    }

    public void setSchool(School school) {
        this.school = school;
    }

    public Student getStudent() {
        return this.student;
    }

    public void setStudent(Student student) {
        this.student = student;
    }

    public Integer getDate() {
        return this.date;
    }

    public void setDate(Integer date) {
        this.date = date;
    }

    public String getDistance() {
        return this.distance;
    }

    public void setDistance(String distance) {
        this.distance = distance;
    }

    public Integer getPastpupilScore() {
        return this.pastpupilScore;
    }

    public void setPastpupilScore(Integer pastpupilScore) {
        this.pastpupilScore = pastpupilScore;
    }

    public Integer getSiblingScore() {
        return this.siblingScore;
    }

    public void setSiblingScore(Integer siblingScore) {
        this.siblingScore = siblingScore;
    }

    public String getDistanceScore() {
        return this.distanceScore;
    }

    public void setDistanceScore(String distanceScore) {
        this.distanceScore = distanceScore;
    }

    public String getRegisteredStatus() {
        return this.registeredStatus;
    }

    public void setRegisteredStatus(String registeredStatus) {
        this.registeredStatus = registeredStatus;
    }

}
