package Model;
// Generated Dec 15, 2015 5:43:23 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * School generated by hbm2java
 */
public class School implements java.io.Serializable {

    private int schoolId;
    private String name;
    private String address;
    private String category;
    private String district;
    private String province;
    private String contactNo;
    private Short flag;
    private Set principals = new HashSet(0);
    private Set registries = new HashSet(0);

    public School() {
    }

    public School(int schoolId) {
        this.schoolId = schoolId;
    }

    public School(int schoolId, String name, String address, String category, String district, String province, String contactNo, Short flag, Set principals, Set registries) {
        this.schoolId = schoolId;
        this.name = name;
        this.address = address;
        this.category = category;
        this.district = district;
        this.province = province;
        this.contactNo = contactNo;
        this.flag = flag;
        this.principals = principals;
        this.registries = registries;
    }

    public School(int schoolId, String name, String address, String category, String district, String province, String contactNo, Short flag) {
        this.schoolId = schoolId;
        this.name = name;
        this.address = address;
        this.category = category;
        this.district = district;
        this.province = province;
        this.contactNo = contactNo;
        this.flag = flag;
    }

    public int getSchoolId() {
        return this.schoolId;
    }

    public void setSchoolId(int schoolId) {
        this.schoolId = schoolId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getCategory() {
        return this.category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getDistrict() {
        return this.district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    public String getProvince() {
        return this.province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getContactNo() {
        return this.contactNo;
    }

    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }

    public Short getFlag() {
        return this.flag;
    }

    public void setFlag(Short flag) {
        this.flag = flag;
    }

    public Set getPrincipals() {
        return this.principals;
    }

    public void setPrincipals(Set principals) {
        this.principals = principals;
    }

    public Set getRegistries() {
        return this.registries;
    }

    public void setRegistries(Set registries) {
        this.registries = registries;
    }

}
