package Model;
// Generated Dec 15, 2015 5:43:23 PM by Hibernate Tools 4.3.1

/**
 * Sibling generated by hbm2java
 */
public class Sibling implements java.io.Serializable {

    private int siblingId;
    private Student sibling;
    private Student student;
    private String admissionNo;
    private String currentGrade;

    public Sibling() {
    }

    public Sibling(int siblingId, Student student) {
        this.siblingId = siblingId;
        this.student = student;
    }

    public Sibling(int siblingId, Student student, String admissionNo, String currentGrade) {
        this.siblingId = siblingId;
        this.student = student;
        this.admissionNo = admissionNo;
        this.currentGrade = currentGrade;
    }

    public Sibling(int siblingId, Student student, Student sibling, String admissionNo, String currentGrade) {
        this.siblingId = siblingId;
        this.student = student;
        this.admissionNo = admissionNo;
        this.currentGrade = currentGrade;
        this.sibling = sibling;
    }

    public int getSiblingId() {
        return this.siblingId;
    }

    public void setSiblingId(int siblingId) {
        this.siblingId = siblingId;
    }

    public Student getStudent() {
        return this.student;
    }

    public void setStudent(Student student) {
        this.student = student;
    }

    public String getAdmissionNo() {
        return this.admissionNo;
    }

    public void setAdmissionNo(String admissionNo) {
        this.admissionNo = admissionNo;
    }

    public String getCurrentGrade() {
        return this.currentGrade;
    }

    public void setCurrentGrade(String currentGrade) {
        this.currentGrade = currentGrade;
    }

    /**
     * @return the sibling
     */
    public Student getSibling() {
        return sibling;
    }

    /**
     * @param sibling the sibling to set
     */
    public void setSibling(Student sibling) {
        this.sibling = sibling;
    }

}
