package Model;
// Generated Dec 15, 2015 5:43:23 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

    private int studentId;
    private Parent parent;
    private String initials;
    private String fullName;
    private String lastName;
    private String dob;
    private String sex;
    private String religion;
    private String medium;
    private Short flag;
    private Set registries = new HashSet(0);
    private Set siblings = new HashSet(0);
    private Set pastPupils = new HashSet(0);

    public Student() {
    }

    public Student(int studentId, Parent parent, String initials) {
        this.studentId = studentId;
        this.parent = parent;
        this.initials = initials;
    }

    public Student(int studentId, Parent parent, String initials, String fullName, String lastName, String dob, String sex, String religion, String medium, Short flag, Set registries, Set siblings, Set pastPupils) {
        this.studentId = studentId;
        this.parent = parent;
        this.initials = initials;
        this.fullName = fullName;
        this.lastName = lastName;
        this.dob = dob;
        this.sex = sex;
        this.religion = religion;
        this.medium = medium;
        this.flag = flag;
        this.registries = registries;
        this.siblings = siblings;
        this.pastPupils = pastPupils;
    }

    public int getStudentId() {
        return this.studentId;
    }

    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }

    public Parent getParent() {
        return this.parent;
    }

    public void setParent(Parent parent) {
        this.parent = parent;
    }

    public String getInitials() {
        return this.initials;
    }

    public void setInitials(String initials) {
        this.initials = initials;
    }

    public String getFullName() {
        return this.fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getDob() {
        return this.dob;
    }

    public void setDob(String dob) {
        this.dob = dob;
    }

    public String getSex() {
        return this.sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getReligion() {
        return this.religion;
    }

    public void setReligion(String religion) {
        this.religion = religion;
    }

    public String getMedium() {
        return this.medium;
    }

    public void setMedium(String medium) {
        this.medium = medium;
    }

    public Short getFlag() {
        return this.flag;
    }

    public void setFlag(Short flag) {
        this.flag = flag;
    }

    public Set getRegistries() {
        return this.registries;
    }

    public void setRegistries(Set registries) {
        this.registries = registries;
    }

    public Set getSiblings() {
        return this.siblings;
    }

    public void setSiblings(Set siblings) {
        this.siblings = siblings;
    }

    public Set getPastPupils() {
        return this.pastPupils;
    }

    public void setPastPupils(Set pastPupils) {
        this.pastPupils = pastPupils;
    }

}
