package Model;
// Generated Dec 15, 2015 5:43:23 PM by Hibernate Tools 4.3.1

/**
 * Telephone generated by hbm2java
 */
public class Telephone implements java.io.Serializable {

    private int userId;
    private User user;
    private String mobileNumber;
    private String landLine;

    public Telephone() {
    }

    public Telephone(User user) {
        this.user = user;
    }

    public Telephone(User user, String mobileNumber, String landLine) {
        this.user = user;
        this.mobileNumber = mobileNumber;
        this.landLine = landLine;
    }

    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getMobileNumber() {
        return this.mobileNumber;
    }

    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    public String getLandLine() {
        return this.landLine;
    }

    public void setLandLine(String landLine) {
        this.landLine = landLine;
    }

}
