package Model;
// Generated Dec 15, 2015 5:43:23 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

    private int userId;
    private String username;
    private String password;
    private String userLevel;
    private String fname;
    private String lname;
    private String nic;
    private String address;
    private String email;
    private Short flag;
    private Telephone telephone;
    private Set parents = new HashSet(0);
    private Set principals = new HashSet(0);
    private Set gramaNiladharis = new HashSet(0);

    public User() {
    }

    public User(int userId, String username, String password, String userLevel) {
        this.userId = userId;
        this.username = username;
        this.password = password;
        this.userLevel = userLevel;
    }

    public User(int userId, String username, String password, String userLevel, String fname, String lname, String nic, String address, String email, Short flag, Telephone telephone, Set parents, Set principals, Set gramaNiladharis) {
        this.userId = userId;
        this.username = username;
        this.password = password;
        this.userLevel = userLevel;
        this.fname = fname;
        this.lname = lname;
        this.nic = nic;
        this.address = address;
        this.email = email;
        this.flag = flag;
        this.telephone = telephone;
        this.parents = parents;
        this.principals = principals;
        this.gramaNiladharis = gramaNiladharis;
    }

    public User(int userId, String username, String password, String userLevel, String fname, String lname, String nic, String address, String email, Short flag, Telephone telephone) {
        this.userId = userId;
        this.username = username;
        this.password = password;
        this.userLevel = userLevel;
        this.fname = fname;
        this.lname = lname;
        this.nic = nic;
        this.address = address;
        this.email = email;
        this.flag = flag;
        this.telephone = telephone;
    }

    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getUserLevel() {
        return this.userLevel;
    }

    public void setUserLevel(String userLevel) {
        this.userLevel = userLevel;
    }

    public String getFname() {
        return this.fname;
    }

    public void setFname(String fname) {
        this.fname = fname;
    }

    public String getLname() {
        return this.lname;
    }

    public void setLname(String lname) {
        this.lname = lname;
    }

    public String getNic() {
        return this.nic;
    }

    public void setNic(String nic) {
        this.nic = nic;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Short getFlag() {
        return this.flag;
    }

    public void setFlag(Short flag) {
        this.flag = flag;
    }

    public Telephone getTelephone() {
        return this.telephone;
    }

    public void setTelephone(Telephone telephone) {
        this.telephone = telephone;
    }

    public Set getParents() {
        return this.parents;
    }

    public void setParents(Set parents) {
        this.parents = parents;
    }

    public Set getPrincipals() {
        return this.principals;
    }

    public void setPrincipals(Set principals) {
        this.principals = principals;
    }

    public Set getGramaNiladharis() {
        return this.gramaNiladharis;
    }

    public void setGramaNiladharis(Set gramaNiladharis) {
        this.gramaNiladharis = gramaNiladharis;
    }

}
